version: "3.7"
services:
  app:
    build:
      context: .
      target: prod
    depends_on:
      - db
    ports:
      - 8080:8080
#    command: ["/opt/bin/wait-for-it.sh", "db:3306", "--", "/server"]
    command: sh -c "sleep 10 && ./server"
#  db:
#    image: mysql
#    ports:
#      - 3306:3306
#    environment:
#      MYSQL_ROOT_PASSWORD: love
#      MYSQL_DATABASE: photolist
#      MYSQL_USER: root
#    volumes:
#      - ./db_init.sql:/docker-entrypoint-initdb.d/db_init.sql

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: love
      POSTGRES_DB: photolist
      POSTGRES_USER: root
    volumes:
      - ./db_init.sql:/docker-entrypoint-initdb.d/db_init.sql